server:
  port: 8080

build.name: @project.name@
build.version: @project.version@

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mmd-schedules
    username: root
    password: mmd-schedules
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false